apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject-cron
  namespace: openproject
  labels:
    app.kubernetes.io/name: openproject
    app.kubernetes.io/instance: openproject-cron
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: cron
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openproject
      app.kubernetes.io/instance: openproject-cron
      app.kubernetes.io/part-of: openproject
      app.kubernetes.io/component: cron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openproject
        app.kubernetes.io/instance: openproject-cron
        app.kubernetes.io/part-of: openproject
        app.kubernetes.io/component: cron
    spec:
      containers:
        - name: openproject-community
          image: openproject/community:12
          command:
            - "./docker/prod/cron"
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: openproject-db-secret
                key: url
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "300m"