apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject-worker
  namespace: openproject
  labels:
    app.kubernetes.io/name: openproject
    app.kubernetes.io/instance: openproject-worker
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openproject
      app.kubernetes.io/instance: openproject-worker
      app.kubernetes.io/part-of: openproject
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openproject
        app.kubernetes.io/instance: openproject-worker
        app.kubernetes.io/part-of: openproject
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: openproject-community
          image: openproject/community:12
          command:
            - "./docker/prod/worker"
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: openproject-db-secret
                key: url
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"