apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openproject-worker
  namespace: openproject
  labels:
    app.kubernetes.io/name: openproject
    app.kubernetes.io/instance: openproject-worker
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openproject-worker
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50