apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-db-config
  namespace: openproject
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: openproject-postgresql
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: openproject
  PGDATA: /data/pgdata