apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-db-config
  namespace: openproject
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: openproject-db
    app.kubernetes.io/part-of: openproject
data:
  POSTGRES_USER: openproject
  POSTGRES_PASSWORD: p4ssw0rd
  POSTGRES_DB: openproject