apiVersion: v1
kind: Service
metadata:
  name: openproject-db
  namespace: openproject
  labels:
    app.kubernetes.io/name: lb
    app.kubernetes.io/part-of: openproject
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: openproject-postgresql
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: database
  type: NodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: postgres
    