apiVersion: v1
kind: Service
metadata:
  name: openproject-db
  namespace: openproject
  labels:
    app.kubernetes.io/name: lb
    app.kubernetes.io/part-of: openproject
spec:
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: openproject-postgresql
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    