apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openproject-db
  namespace: openproject
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: openproject-postgresql
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: database
spec:
  serviceName: openproject-db
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: openproject-postgresql
      app.kubernetes.io/part-of: openproject
      app.kubernetes.io/component: database
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: openproject-postgresql
        app.kubernetes.io/part-of: openproject
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: postgresql-db
        image: postgres:13
        ports:
          - containerPort: 5342
        volumeMounts:
        - name: openroject-db-data-2
          mountPath: /data
        envFrom:
        - configMapRef:
            name: openproject-db-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: openproject-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openproject-db-secret
              key: password
  volumeClaimTemplates:
    - metadata:
        name: openroject-db-data-2
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi