apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject-web
  namespace: openproject
  labels:
    app.kubernetes.io/name: openproject
    app.kubernetes.io/instance: openproject-web
    app.kubernetes.io/part-of: openproject
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openproject
      app.kubernetes.io/instance: openproject-web
      app.kubernetes.io/part-of: openproject
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openproject
        app.kubernetes.io/instance: openproject-web
        app.kubernetes.io/part-of: openproject
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: openproject-community
          image: openproject/community:12
          command:
            - "./docker/prod/web"
          env:
          - name: DATABASE_URL 
            valueFrom:
              secretKeyRef:
                name: openproject-db-secret
                key: url
          - name: OPENPROJECT_CACHE__MEMCACHE__SERVER
            value: openproject-cache:11211
          - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
          - name: OPENPROJECT_RAILS__CACHE_STORE
            value: memcache
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"