apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openproject-web
  namespace: openproject
  labels:
    app.kubernetes.io/name: openproject-community
    app.kubernetes.io/instance: openproject-web
    app.kubernetes.io/part-of: openproject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openproject-web
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10