apiVersion: v1
kind: ConfigMap
metadata:
  name: php-echo-config
  namespace: hello
  labels:
    app.kubernetes.io/name: php-echo
    app.kubernetes.io/instance: php-echo
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: php-echo
data:
  index.php: >-
    <? phpinfo();