apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-echo
  namespace: hello
  labels:
    app.kubernetes.io/name: php-echo
    app.kubernetes.io/instance: php-echo
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: php-echo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-echo
      app.kubernetes.io/instance: php-echo
      app.kubernetes.io/part-of: hello
      app.kubernetes.io/component: php-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-echo
        app.kubernetes.io/instance: php-echo
        app.kubernetes.io/part-of: hello
        app.kubernetes.io/component: php-echo
    spec:
      containers:
        - name: php
          image: php:7.2-apache
          ports:
          - containerPort: 80
          volumeMounts:
            - name: app
              mountPath: /var/www/html/
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "5m"
            limits:
              memory: "64Mi"
              cpu: "5m"
      volumes:
        - name: app
          configMap:
            name: php-echo-config