apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-echo
  namespace: hello
  labels:
    app.kubernetes.io/name: php-echo
    app.kubernetes.io/instance: php-echo
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: php-echo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-echo
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50