apiVersion: v1
kind: Service
metadata:
  name: php-echo
  namespace: hello
  labels:
    app.kubernetes.io/name: cip
    app.kubernetes.io/part-of: hello
spec:
  selector:
    app.kubernetes.io/name: php-echo
    app.kubernetes.io/instance: php-echo
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: php-echo
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    