apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdm-presentation
  namespace: hello
  labels:
    app.kubernetes.io/name: vdm-presentation
    app.kubernetes.io/instance: vdm-presentation
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: vdm-presentation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vdm-presentation
      app.kubernetes.io/instance: vdm-presentation
      app.kubernetes.io/part-of: hello
      app.kubernetes.io/component: vdm-presentation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vdm-presentation
        app.kubernetes.io/instance: vdm-presentation
        app.kubernetes.io/part-of: hello
        app.kubernetes.io/component: vdm-presentation
    spec:
      containers:
        - name: vdm-presentation
          image: docker.io/thund/vdm-presentation
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "5m"
            limits:
              memory: "64Mi"
              cpu: "5m"