apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vdm-presentation
  namespace: hello
  labels:
    app.kubernetes.io/name: vdm-presentation
    app.kubernetes.io/instance: vdm-presentation
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: vdm-presentation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vdm-presentation
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50