apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: nginx
data:
  nginx.conf: >-
    events {
        use           epoll;
        worker_connections  128;
    }

    http {
      server {
        listen 80;
        
        location = /index.html {
          proxy_pass http://vdm-presentation:80;
        }

        location /OutDocument {
          proxy_pass http://vdm-presentation:80;
        }

        location = /info {
          proxy_pass http://php-echo:80/;
        }
      }
    }