apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hello
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/part-of: hello
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/part-of: hello
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          command:
            - "nginx"
            - "-g"
            - "daemon off;"
          env:
            - name: NGINX_PORT
              value: "80"
          volumeMounts:
            - name: app
              mountPath: /etc/nginx
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "5m"
            limits:
              memory: "64Mi"
              cpu: "5m"
      volumes:
        - name: app
          configMap:
            name: nginx-config