apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: hello
  labels:
    app.kubernetes.io/name: lb
    app.kubernetes.io/part-of: hello
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/part-of: hello
    app.kubernetes.io/component: nginx
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
    